version: '3.7'

networks:
  adesnet:
    driver: bridge

services:
    webapi:
        image: ${DOCKER_REGISTRY-}webapi
        depends_on:
            - "adessibinden_db"
        container_name: adessibindenAPI
        ports:
            - 5000:5000
            - 5001:5001  
        build: 
          context: .
          dockerfile: src/WebAPI/Dockerfile
        networks:
            - adesnet

    adessibinden_db:
        image: postgres
        container_name: 'postgres'
        environment:
            - POSTGRES_USER=<YOUR USERNAME>
            - POSTGRES_PASSWORD=<YOUR PASSWORD>
            - POSTGRES_DB=adessbindenDbDocker
        restart: always
        ports:
            - 5432:5432
        volumes:
            - adessibinden_data:/var/lib/postgresql/data/
        networks:
            - adesnet
    adessibinden_frontend:
        build: ../AdessibindenFrontend
        container_name: 'adessibinden_frontend'
        ports:
            - 8080:8080
        depends_on:
            - "webapi"
        networks:
            - adesnet
 
 
volumes:
    adessibinden_data:    